### ISSUE TITLE
Getting an error while calling a HTTPS WSDL

### ISSUE THREAD

**Issue by GurpreetVirdi** [adrin-mukherjee/lambda_rest2soap#2]
I am getting the following error while calling an HTTPS WSDL : 

Response:
{
  "errorType": "TypeError",
  "errorMessage": "Cannot read property 'getCaseInformation' of undefined",
  "trace": [
    "TypeError: Cannot read property 'getCaseInformation' of undefined",
    "    at /var/task/index.js:29:20",
    "    at /var/task/node_modules/soap/lib/soap.js:84:9",
    "    at /var/task/node_modules/soap/lib/soap.js:39:28",
    "    at /var/task/node_modules/soap/lib/wsdl/index.js:1245:17",
    "    at Request._callback (/var/task/node_modules/soap/lib/http.js:159:28)",
    "    at self.callback (/var/task/node_modules/request/request.js:185:22)",
    "    at Request.emit (events.js:314:20)",
    "    at Request.onRequestError (/var/task/node_modules/request/request.js:877:8)",
    "    at ClientRequest.emit (events.js:314:20)",
    "    at TLSSocket.socketErrorListener (_http_client.js:428:9)",
    "    at TLSSocket.emit (events.js:314:20)",
    "    at emitErrorNT (internal/streams/destroy.js:92:8)",
    "    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)",
    "    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
  ]
}

Request ID:
"a97dcfce-21cb-41ac-acc6-0d6b73175643"

Function logs:
START RequestId: a97dcfce-21cb-41ac-acc6-0d6b73175643 Version: $LATEST
2021-01-07T06:53:45.633Z	a97dcfce-21cb-41ac-acc6-0d6b73175643	INFO	Event >>  { caseNumIdentif: '20316712' }
2021-01-07T06:53:45.671Z	a97dcfce-21cb-41ac-acc6-0d6b73175643	INFO	Transformed Request >> [object Object]
2021-01-07T06:53:46.311Z	a97dcfce-21cb-41ac-acc6-0d6b73175643	ERROR	Uncaught Exception 	{"errorType":"TypeError","errorMessage":"Cannot read property 'getCaseInformation' of undefined","stack":["TypeError: Cannot read property 'getCaseInformation' of undefined","    at /var/task/index.js:29:20","    at /var/task/node_modules/soap/lib/soap.js:84:9","    at /var/task/node_modules/soap/lib/soap.js:39:28","    at /var/task/node_modules/soap/lib/wsdl/index.js:1245:17","    at Request._callback (/var/task/node_modules/soap/lib/http.js:159:28)","    at self.callback (/var/task/node_modules/request/request.js:185:22)","    at Request.emit (events.js:314:20)","    at Request.onRequestError (/var/task/node_modules/request/request.js:877:8)","    at ClientRequest.emit (events.js:314:20)","    at TLSSocket.socketErrorListener (_http_client.js:428:9)","    at TLSSocket.emit (events.js:314:20)","    at emitErrorNT (internal/streams/destroy.js:92:8)","    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)","    at processTicksAndRejections (internal/process/task_queues.js:84:21)"]}
END RequestId: a97dcfce-21cb-41ac-acc6-0d6b73175643
REPORT RequestId: a97dcfce-21cb-41ac-acc6-0d6b73175643	Duration: 916.25 ms	Billed Duration: 917 ms	Memory Size: 128 MB	Max Memory Used: 40 MB	
Unknown application error occurred

**Comment by GurpreetVirdi** [comment]
its an HTTPS service running on port 443. 

i think we need to pass some params for https but i am new to node.js

any help would be much appreciated

**Comment by adrin-mukherjee** [comment]
@GurpreetVirdi- If the service integration requires mutual TLS (or two way SSL), then some additional parameters needs to be passed. However, for simple HTTPS endpoints, nothing additional is required. 
Having said that, please create issues if they are linked to the code in this repo. For issues pertaining to your code, I'd suggest you create issues in platforms like stackoverflow for effective response.
Hope this helps
